# Generated by Django 4.2.7 on 2023-12-23 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Name', models.CharField(max_length=100)),
                ('Car_Model', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brand.brandmodel')),
            ],
        ),
    ]
