# Generated by Django 4.2.7 on 2023-12-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_carmodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Car/media/uploads/'),
        ),
    ]
