# Generated by Django 4.2.7 on 2023-12-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_carmodel_slug_alter_carmodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='slug',
        ),
    ]
